/**
 * Manual Saudi location hierarchy (focus: Al-Ahsa).
 *
 * Edit this file when you need to add/remove locations.
 * Structure:
 * Governorate -> city/cluster -> areas (districts/villages/neighborhoods)
 */

const AL_AHSA_GOVERNORATE = "الأحساء";

const LOCATION_HIERARCHY = {
  [AL_AHSA_GOVERNORATE]: {
    // Administrative context (optional, won't break your current structure)
    region: "المنطقة الشرقية",
    aliases: [
      "الأحساء",
      "الاحساء",
      "الأحسا",
      "الاحسا",
      "الحسا",
      "الأحساء (الحسا)",
      "واحة الأحساء",
      "Al Ahsa",
      "Al-Ahsa",
      "Al Hasa",
      "Al-Hasa",
      "Alhasa",
      "Hasa",
      "Al Ahsa Oasis",
    ],

    cities: {
      الهفوف: {
        type: "city",
        aliases: [
          "الهفوف",
          "هفوف",
          "الهفوف الاحساء",
          "هفوف الاحساء",
          "Al Hofuf",
          "Hofuf",
          "Al-Hofuf",
        ],
        // Mix of (1) Wikipedia neighborhoods list + (2) commonly used neighborhood names in listings
        areas: [
          // Wikipedia list (high-confidence)
          "الرقيقة",
          "صويدرة",
          "الشهابية",
          "الصالحية",
          "البصيرة",
          "القادسية",
          "السلمانية الشمالية",
          "السلمانية الجنوبية",
          "الصيهد",
          "المحمدية",
          "النزهة",
          "الروضة",
          "الفاضلية",
          "عين موسى",
          "الرفعة الجنوبية",
          "البندرية",
          "السنيدية",
          "النايفية",
          "المحدود",
          "الكوت",

          // Practical/market-used expansions (useful for user input matching)
          "المربدية",
          "السلام",
          "المباركية",
          "المزروع",
          "الخالدية",
          "العويمرية",
          "الحفيرة",
          "الهدى",
          "النسيم",
          "الورود",
          "الواحة",
          "المروج",
          "المرقاب",
          "اللويمي",
          "القدس",
          "المدينة الرياضية",
          "منسوبي التعليم",
          "المهندسين",
          "المطار",
          "الناصرية",
          "الرابية",
          "جوبا",
        ],
      },

      المبرز: {
        type: "city",
        aliases: [
          "المبرز",
          "مبرز",
          "المبرز الاحساء",
          "Al Mubarraz",
          "Mubarraz",
          "Al-Mubarraz",
        ],
        // Wikipedia list + practical expansions
        areas: [
          // Wikipedia list (high-confidence)
          "الأندلس",
          "الحزم",
          "عين النجم",
          "محاسن",

          // محاسن تفريعات شائعة
          "محاسن أرامكو",
          "محاسن البلدية",
          "محاسن القادسية",

          // Practical/market-used expansions (useful for user input matching)
          "النزهة",
          "الراشدية",
          "وسط المبرز التاريخي",
          "محيرس",
          "مشرفة",
          "مدينة الملك عبدالله العسكرية",
          "قرطبة",
          "عين مرجان",
          "بو سحبل",
          "اليمامة",
          "اليرموك",
          "الياسمين",
          "المقابل",
          "المسعودي",
          "الفيصل",
          "الفنار",
          "الفتح",
          "الضباب",
          "الصناعية",
          "الشعبة",
          "الشروفية",
          "الشراع الشمالي",
          "الشراع الجنوبي",
          "السلام الأول",
          "السلام الثاني",
          "السحيمية",
        ],
      },

      العيون: {
        type: "town",
        aliases: [
          "العيون",
          "عيون",
          "العيون الاحساء",
          "Al Uyoun",
          "Al Uyun",
          "Oyoun",
        ],
        areas: [
          "الديرة القديم",
          "المعيزل",
          "الرفاع",
          "الحصيمه",
          "النسيم الأول",
          "النسيم الثاني",
          "المدينة الصناعية",
          "الصناعية الخارجية",
          "القطّار",
          "السلطانية 1",
          "السلطانية 2",
          "السلطانية 3",
          "المقربيه",
          "مخطط شمال العقير",
          "مخطط الرابية",
          "المزارع الشمالية",
          "المزارع الشرقية",
          "المزارع الجنوبية",
        ],
      },

      العمران: {
        type: "town",
        aliases: [
          "العمران",
          "العُمران",
          "العمران الاحساء",
          "Al Umran",
          "Umran",
        ],
        // You already have many عمران-sub entries inside "القرى" — keeping them here helps matching.
        areas: [
          "العمران (أبوالحصا)",
          "العمران (الرمل)",
          "العمران (الحوطة)",
          "العمران (أبو ثور)",
          "العمران (السبايخ)",
          "العمران (الديوية)",
          "العمران (الشويكية)",
          "العمران (الأسلة)",
          "العمران (العرامية)",
          "العمران (التويثير)",
        ],
      },

      // Big villages/towns that people often type as “city” in forms
      الطرف: {
        type: "village",
        aliases: ["الطرف", "طرف", "الطرف (السعدون)", "الطرف (العدوة)"],
        areas: [],
      },
      البطالية: { type: "village", aliases: ["البطالية", "بطالية"], areas: [] },
      الكلابية: { type: "village", aliases: ["الكلابية", "كلابية"], areas: [] },
      المطيرفي: {
        type: "village",
        aliases: ["المطيرفي", "المطيرفية"],
        areas: [],
      },
      المنيزلة: { type: "village", aliases: ["المنيزلة", "منيزلة"], areas: [] },
      الجفر: { type: "village", aliases: ["الجفر", "جفر"], areas: [] },
      الفضول: { type: "village", aliases: ["الفضول", "فضول"], areas: [] },
      القارة: { type: "village", aliases: ["القارة", "قارة"], areas: [] },
      الرميلة: { type: "village", aliases: ["الرميلة", "رميلة"], areas: [] },
      الحليلة: { type: "village", aliases: ["الحليلة", "حليلة"], areas: [] },
      العقير: {
        type: "area",
        aliases: ["العقير", "ميناء العقير", "Al Uqair"],
        areas: [],
      },
      جواثا: {
        type: "area",
        aliases: ["جواثا", "جوااثا", "Jawatha"],
        areas: [],
      },

      // Backward compatible bucket (your original approach)
      القرى: {
        type: "bucket",
        aliases: [
          "القرى",
          "القرى والهجر",
          "القرى و الهجر",
          "الهجر",
          "قرى الأحساء",
          "هجر الأحساء",
        ],
        areas: [
          // (kept from your list) — you can keep extending this bucket freely
          "المنيزلة",
          "المروج",
          "الفضول",
          "الشهارين",
          "المنصورة",
          "المزاوي",
          "العقار",
          "الساباط",
          "الجفر",
          "غمسي",
          "التهيمية",
          "السيايرة",
          "الجبيل",
          "الطريبيل",
          "الدالوة",

          // عمران sub-entries
          "العمران (أبوالحصا)",
          "العمران (الرمل)",
          "العمران (الحوطة)",
          "العمران (أبو ثور)",
          "العمران (السبايخ)",
          "العمران (الديوية)",
          "العمران (الشويكية)",
          "العمران (الأسلة)",
          "العمران (العرامية)",
          "العمران (التويثير)",

          "القارة",
          "الرميلة",
          "الدويكية",
          "جواثا",
          "العلية",
          "واسط",
          "صويدره",
          "بني معن",
          "جليجلة",
          "المراح",
          "الصفا",
          "القرن",
          "الشقيق",
          "الوزية",
          "العقير",
          "الشروق",
          "الوادي",
          "مثلث الشرقية",
          "الثريا",
          "ابوحريف",
          "الجرن",
          "القرين",
          "الشعبة",
          "المطيرفي",
          "المطيرفية",
          "المقدام",
          "الكلابية",
          "الحليلة",
          "البطالية",
          "الطرف (السعدون)",
          "الطرف (العدوة)",
          "الطرف",

          // Add latin-digit variants (optional but helps if user types 1 not ١)
          "ضاحية هجر ١",
          "ضاحية هجر ٢",
          "ضاحية هجر ٣",
          "ضاحية هجر ٤",
          "ضاحية هجر ٥",
          "ضاحية هجر ٦",
          "ضاحية هجر ٧",
          "ضاحية هجر ٨",
          "ضاحية هجر ٩",
          "ضاحية هجر ١٠",
          "ضاحية هجر ١١",
          "ضاحية هجر ١٢",
          "ضاحية هجر 1",
          "ضاحية هجر 2",
          "ضاحية هجر 3",
          "ضاحية هجر 4",
          "ضاحية هجر 5",
          "ضاحية هجر 6",
          "ضاحية هجر 7",
          "ضاحية هجر 8",
          "ضاحية هجر 9",
          "ضاحية هجر 10",
          "ضاحية هجر 11",
          "ضاحية هجر 12",

          "الضاحية (التعاون)",
          "الجشة (الخزامى)",
          "الجشة (البريد)",
          "الجشة",
          "النخيل",
          "المركز (النور)",
          "المركز (السعدون)",
        ],
      },
    },
  },
};

const DEFAULT_WP_BEFORE_CITY_OPTIONS = Object.keys(LOCATION_HIERARCHY);
const DEFAULT_WP_CITY_OPTIONS = Object.keys(
  LOCATION_HIERARCHY[AL_AHSA_GOVERNORATE].cities || {},
);

module.exports = {
  LOCATION_HIERARCHY,
  AL_AHSA_GOVERNORATE,
  DEFAULT_WP_BEFORE_CITY_OPTIONS,
  DEFAULT_WP_CITY_OPTIONS,
};
